### PR TITLE
Link to trinity repo and docs on home page

### PR DESCRIPTION
**Pull request by carver**
Tangential: is `support@trinity.io` actually a monitored email address? If not, I can either remove it or update it.

### CODE REVIEW

**Comment by carver** [comment]
Also, what's the deployment process here. Does pushing to master auto-deploy?

**Comment by pipermerriam** [comment]
Yes, it is github pages sourcing from `master` branch.

**Review by pipermerriam — APPROVED** [review]

**Comment by carver** [comment]
Is support@trinity.io a monitored email address?

**Comment by pipermerriam** [comment]
No, and I don't even think we have `trinity.io`

**Pull request merged**
